apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ucqm-argo
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  destination:
    namespace: mq01-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: yaml/
    repoURL: https://github.com/sandepal/mq-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true